In [6]:
import json
with open (r"C:\Users\Bijan Emadi\.secret\yelp_api.json") as f:
    login = json.load(f)
login.keys()

dict_keys(['client-id', 'api-key'])

In [7]:
# import the YelpAPI Class
from yelpapi import YelpAPI
# Create an instance with your key
yelp_api = YelpAPI(login['api-key'], timeout_s=5.0)
yelp_api

In [8]:
help(yelp_api.search_query)

Help on method search_query in module yelpapi.yelpapi:

search_query(**kwargs) method of yelpapi.yelpapi.YelpAPI instance
    Query the Yelp Search API.

    documentation: https://www.yelp.com/developers/documentation/v3/business_search

    required parameters:
        * one of either:
            * location - text specifying a location to search for
            * latitude and longitude

In [9]:
# use our yelp_api variable's search_query method to perform our API call
search_results = yelp_api.search_query(location='Baltimore, MD,21202',
                                       term='Crab Cakes')
print(type(search_results))
search_results.keys()

<class 'dict'>

dict_keys(['businesses', 'total', 'region'])

In [10]:
search_results['total']

433

In [15]:
import pandas as pd

In [17]:
biz = pd.DataFrame(search_results['businesses'])
biz.head(2)

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,ieS_5zqxDHcWMCm8BKUYbg,thames-street-oyster-house-baltimore,Thames Street Oyster House,https://s3-media1.fl.yelpcdn.com/bphoto/9hGjo5...,False,https://www.yelp.com/biz/thames-street-oyster-...,2747,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",4.5,"{'latitude': 39.28214, 'longitude': -76.59162}",[delivery],$$$,"{'address1': '1728 Thames St', 'address2': '',...",+14434497726,(443) 449-7726,2090.712792
1,D9A33FM394q99o4QtK5YwA,faidleys-seafood-baltimore-3,Faidley's Seafood,https://s3-media3.fl.yelpcdn.com/bphoto/8j3ynZ...,False,https://www.yelp.com/biz/faidleys-seafood-balt...,1195,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",4.0,"{'latitude': 39.291696, 'longitude': -76.62224}",[delivery],$$,"{'address1': '203 N Paca St', 'address2': '', ...",+14107274898,(410) 727-4898,1349.560720

In [18]:
## total number of matching businesses
search_results['total']

433

In [19]:
## how many businesses in our results
len(search_results['businesses'])

20

In [20]:
# add offset to our original api call
search_results = yelp_api.search_query(location='Baltimore, MD,21202',
                                       term='Crab Cakes',
                                       offset = 20)

In [21]:
biz20 = pd.DataFrame(search_results['businesses'])
biz20.head(2)

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,s0LPuaTzR9euWzNT52o49Q,sugarbees-cafe-and-grill-baltimore-5,Sugarbee's Cafe & Grill,https://s3-media2.fl.yelpcdn.com/bphoto/wJdfsJ...,False,https://www.yelp.com/biz/sugarbees-cafe-and-gr...,37,"[{'alias': 'tradamerican', 'title': 'American ...",4.0,"{'latitude': 39.29205, 'longitude': -76.61585}","[delivery, pickup]",$,"{'address1': '222 N Charles St', 'address2': '...",+14104430475,(410) 443-0475,840.660168
1,TPQmNAM2g1vmm2xCfhyEJw,pratt-street-ale-house-baltimore,Pratt Street Ale House,https://s3-media4.fl.yelpcdn.com/bphoto/GHyW4Q...,False,https://www.yelp.com/biz/pratt-street-ale-hous...,817,"[{'alias': 'pubs', 'title': 'Pubs'}, {'alias':...",3.5,"{'latitude': 39.2865982055664, 'longitude': -7...","[delivery, pickup]",$$,"{'address1': '206 W Pratt St', 'address2': '',...",+14102448900,(410) 244-8900,1403.278532

In [22]:
## concatenate the previous results and new results. 
businesses = pd.concat([biz, biz20],
                      ignore_index=True)
display(businesses.head(3), businesses.tail(3))

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,ieS_5zqxDHcWMCm8BKUYbg,thames-street-oyster-house-baltimore,Thames Street Oyster House,https://s3-media1.fl.yelpcdn.com/bphoto/9hGjo5...,False,https://www.yelp.com/biz/thames-street-oyster-...,2747,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",4.5,"{'latitude': 39.28214, 'longitude': -76.59162}",[delivery],$$$,"{'address1': '1728 Thames St', 'address2': '',...",+14434497726,(443) 449-7726,2090.712792
1,D9A33FM394q99o4QtK5YwA,faidleys-seafood-baltimore-3,Faidley's Seafood,https://s3-media3.fl.yelpcdn.com/bphoto/8j3ynZ...,False,https://www.yelp.com/biz/faidleys-seafood-balt...,1195,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",4.0,"{'latitude': 39.291696, 'longitude': -76.62224}",[delivery],$$,"{'address1': '203 N Paca St', 'address2': '', ...",+14107274898,(410) 727-4898,1349.560720
2,u65W69AhbjUlvJJBkEhGNQ,miss-shirleys-cafe-baltimore-9,Miss Shirley's Cafe,https://s3-media4.fl.yelpcdn.com/bphoto/9FsOyV...,False,https://www.yelp.com/biz/miss-shirleys-cafe-ba...,2959,"[{'alias': 'breakfast_brunch', 'title': 'Break...",4.0,"{'latitude': 39.2870995, 'longitude': -76.6053...",[delivery],$$,"{'address1': '750 E Pratt St', 'address2': '',...",+14105285373,(410) 528-5373,1028.736468

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
37,heDO_cYM7C-BXmh17sMR-Q,avenue-kitchen-and-bar-baltimore,Avenue Kitchen & Bar,https://s3-media2.fl.yelpcdn.com/bphoto/qzmlw6...,False,https://www.yelp.com/biz/avenue-kitchen-and-ba...,311,"[{'alias': 'newamerican', 'title': 'American (...",4.0,"{'latitude': 39.330862, 'longitude': -76.631807}","[restaurant_reservation, pickup, delivery]",$$,"{'address1': '911 W 36th St', 'address2': None...",+14439618515,(443) 961-8515,4380.308991
38,pJuoa35eDPRXLf7kUbpMTg,the-choptank-baltimore,The Choptank,https://s3-media3.fl.yelpcdn.com/bphoto/0Mdtr7...,False,https://www.yelp.com/biz/the-choptank-baltimor...,207,"[{'alias': 'seafood', 'title': 'Seafood'}]",4.0,"{'latitude': 39.283338, 'longitude': -76.593321}",[],NaN,"{'address1': '1641 Aliceanna St', 'address2': ...",+14437073364,(443) 707-3364,1891.591150
39,TL34QOmDmMtJmsabvPLErg,annabel-lee-tavern-baltimore,Annabel Lee Tavern,https://s3-media2.fl.yelpcdn.com/bphoto/dh6k0b...,False,https://www.yelp.com/biz/annabel-lee-tavern-ba...,611,"[{'alias': 'pubs', 'title': 'Pubs'}, {'alias':...",4.5,"{'latitude': 39.28538, 'longitude': -76.56961}","[restaurant_reservation, pickup, delivery]",$$,"{'address1': '601 S Clinton St', 'address2': '...",+14105222929,(410) 522-2929,3485.045821